#pragma once

typedef enum ActorType{
	FOOD, WATER, OBSTACLE, AGENT, NONE
};

typedef enum CamEnum
{
	PERSPECTIVE, ORTHO, FOLLOWING, POSITION, AIMAT, UPDIRECTION, ASPECT,
	YANGLE, BLACK, WHITE, RED, GREEN, YELLOW, BLUE, MAGENTA, CYAN, GREY,
	WIDTH, HEIGHT, DEPTH, AMBIENT, DIFFUSE, SPECULAR, SPOT_DIRECTION,
	DROPOFFRATE, CUTOFFANGLE, EMISSION, SHININESS, TRANSLATION,
	ROTATION, SCALE, BUFFER, SINGLE, MDOUBLE, RADIUS, STYLE, POINTSIZE,
	LINEWIDTH, FILLED, LINE, MPOINT, BACKCOLOUR, MLEFT, MRIGHT, MTOP, MBOTTOM, MNEAR, MFAR
};